name: AWS S3 deployment using terraform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # For enabling "Run workflow" button in the Github UI

jobs:
  terraform:
    name: 'aws-s3-deployment'
    runs-on: ubuntu-latest
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
    
    #### Required for OIDC ####
    permissions:
      id-token: write  # Required for OIDC token exchange
      contents: read   # Required to checkout the repo
    ###########################

    steps:
    - name: Checkout
      uses: actions/checkout@v4
     # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        # aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        # aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        role-to-assume: arn:aws:iam::026579986315:role/githubA-cicd-terraform-assume-role  # Configure AWS Credentials via OpenID Connect(OIDC) assume role
        aws-region: us-east-1

    - name: Validate AWS CLI access by listing all AWS s3 buckets
      run: aws s3 ls
      
    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init

      # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Validate
      run: terraform validate

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform plan -input=false
      
    - name: Terraform Apply
      if: github.event_name == 'push'
      run: terraform apply -auto-approve -input=false
